#!/bin/sh

# From MDToolkit template file: anvil_lmp.sh

# === README ===
# This script is designed to be submitted from inside a user-created, run-specific directory in the home space. The directory should only contain:
#   - This script
#   - The LAMMPS input file for the run
#   - Any data/restart file(s) required for the run to begin - make sure these are backed up somewhere else! They will be moved into the scratch space, not copied.
# The script will create an identical directory structure at the SCRATCH_DIR location, which is where dump/restart files will be generated.
# Any .txt files generated by LAMMPS via fix commands should be automatically copied back to the home space after the run, unless the job terminates due to an error or timeout.
# The LAMMPS log file, however, will be generated directly on the home space.
# So if the simulation runs to completion, the only action that should be required is to back up any dump/restart files that you want from the SCRATCH_DIR space.



# vvv REPLACE THE {{FIELDS}} vvv

# Partitions info - all nodes have 128 cores
# NOTE: wholenode and wide are node-exclusive (a whole node will be reserved and charged to you even if you request a partial node)
# debug: max 2 hours and 2 nodes per job, max 1 job at a time
# shared (default): max 96 hours and 1 node per job, max 1280 cores queued in total
# wholenode (node-exclusive): max 96 hours and 16 nodes per job, max 64 jobs at a time
# wide (node-exclusive): max 12 hours and 56 nodes per job, max 5 jobs at a time

#SBATCH -A mch250010
#SBATCH --partition={{debug, shared, wholenode, wide}}
#SBATCH --time={{d-hh:mm:ss}}
#SBATCH --nodes={{n}}
#SBATCH --ntasks-per-node={{128}}
#SBATCH --job-name={{name}}
#SBATCH --output="job.%j.%N.out"
#SBATCH --mail-type=ALL
#SBATCH --mail-user={{email}}

# User's scratch directory where dumps and restarts will be generated; must end with a forward slash /
SCRATCH_DIR=$SCRATCH/

# Absolute path to the Spack setup-env.sh file
SPACK_SETUP_PATH=$PROJECT/spack/share/spack/setup-env.sh

# Directory where the user's spack environment view is located (the same directory where slurm_install_md.sh was executed from)
SPACK_ENV_DIR=$HOME/md_env/



# ====================================
# THE REST OF THIS SHOULD BE AUTOMATIC
# ====================================

RUN_DIR_HOME="$PWD/"
RUN_DIR_RELATIVE="${PWD##$HOME/}/"
RUN_DIR_SCRATCH="$SCRATCH_DIR$RUN_DIR_RELATIVE"

# Prevent overwriting an existing run by checking if there is already a directory in the scratch space with the same name
if [ -d $RUN_DIR_SCRATCH ]; then
    echo "ERROR Scratch run directory already exists: $RUN_DIR_SCRATCH"
    exit 1
# Make sure there is exactly one LAMMPS input file for this run
elif [ $(find $RUN_DIR_HOME -maxdepth 1 -name "*.in" | wc -l) -ne 1 ]; then
    echo "ERROR There must be exactly one .in file in the home run directory."
    exit 1
fi

IN_PATH_HOME=$(find $RUN_DIR_HOME -maxdepth 1 -name "*.in")
IN_PATH_RELATIVE=${IN_PATH_HOME##$RUN_DIR_HOME}

# Create identical run directory structure on the scratch space and copy LAMMPS input file there
mkdir -p $RUN_DIR_SCRATCH
cp $IN_PATH_RELATIVE $RUN_DIR_SCRATCH

# Move any data/restart files to the scratch destination; first copy them and then ensure the copy is identical before deleting the original
shopt -s nullglob
for data_restart_file in *.data *.restart *.rs; do
    cp $data_restart_file $RUN_DIR_SCRATCH
    if cmp -s $data_restart_file "$RUN_DIR_SCRATCH$data_restart_file"; then
        rm $data_restart_file
    else
        echo "ERROR failed to copy $data_restart_file into scratch space, or the file was copied but is not identical to the original."
        exit 1
    fi
done

# Activate spack environment
cd $SPACK_ENV_DIR
. $SPACK_SETUP_PATH
spack env activate .

# Switch to the new run directory on the scratch space and start the run
# Write LAMMPS log to the home space
cd $RUN_DIR_SCRATCH
mpirun -np $SLURM_NTASKS `which lmp` -in $IN_PATH_RELATIVE -log "${RUN_DIR_HOME}log.lammps"

# After the run, copy any txt files generated by LAMMPS back to the home space
if [ $(find $RUN_DIR_SCRATCH -maxdepth 1 -name "*.txt" | wc -l) -gt 0 ]; then
    mkdir -p $RUN_DIR_HOME/results
    cp *.txt $RUN_DIR_HOME/results/
fi

exit