#!/bin/sh

# From MDToolkit template file: ookami.sh

# === README ===
# This script is designed to be submitted from inside a user-created, run-specific directory on the home space. The directory should only contain:
#   - This script
#   - The LAMMPS input file for the run
#   - Any data/restart file(s) required for the run to begin
# The script will create an identical directory structure on the scratch space, which is where dump/restart files will be generated.
# Any .txt files generated by LAMMPS via fix commands should be automatically copied back to the home space after the run (unless the job exceeds its time limit).
# However, the LAMMPS log file will be generated directly on the home space.
# If the simulation runs to completion, the only action that should be required is to back up any dump/restart files that you want from the scratch space.



# vvv REPLACE THE {{FIELDS}} vvv

# Ookami partitions: short (4h), medium (12h), long (2d), extended (17d)
#SBATCH --partition={{short, medium, long, extended}}
#SBATCH --time={{d-hh:mm:ss}}
#SBATCH --nodes={{n}}
#SBATCH --ntasks-per-node=48
#SBATCH --job-name {{name}}
#SBATCH --output="job.%j.%N.out"

# User's scratch space directory; must end with a forward slash /
SCRATCH_DIR=/lustre/scratch/$USER/



# The rest of this should be automatic

RUN_DIR_HOME="$PWD/"
RUN_DIR_RELATIVE="${PWD##$HOME/}/"
RUN_DIR_SCRATCH="$SCRATCH_DIR$RUN_DIR_RELATIVE"

# Prevent overwriting an existing run by checking if there is already a directory in the scratch space with the same name
if [ -d $RUN_DIR_SCRATCH ]; then
    echo "ERROR Scratch run directory already exists: $RUN_DIR_SCRATCH"
    exit 1
# Make sure there is exactly one LAMMPS input file for this run
elif [ $(find $RUN_DIR_HOME -name "*.in" | wc -l) -ne 1 ]; then
    echo "ERROR There must be exactly one .in file in the home run directory."
    exit 1
fi

IN_PATH_HOME=$(find $RUN_DIR_HOME -name "*.in")
IN_PATH_RELATIVE=${IN_PATH_HOME##$RUN_DIR_HOME}

# Create identical run directory structure on the scratch space, copy LAMMPS input file there and move any data/restart files there
mkdir -p $RUN_DIR_SCRATCH
cp $IN_PATH_RELATIVE $RUN_DIR_SCRATCH
if [ $(find $RUN_DIR_HOME -name "*.data" | wc -l) -gt 0 ]; then
    mv *.data $RUN_DIR_SCRATCH
fi
if [ $(find $RUN_DIR_HOME -name "*.restart" | wc -l) -gt 0 ]; then
    mv *.restart $RUN_DIR_SCRATCH
fi
if [ $(find $RUN_DIR_HOME -name "*.rs" | wc -l) -gt 0 ]; then
    mv *.rs $RUN_DIR_SCRATCH
fi

# Switch to the new run directory on the scratch space and start the run
# Write LAMMPS log to the home space instead of scratch
cd $RUN_DIR_SCRATCH
module purge
module load slurm
module load lammps/gcc13.2.0/29Sept2024
mpirun -np $SLURM_NTASKS lmp_mpi -in $IN_PATH_RELATIVE -log "${RUN_DIR_HOME}log.lammps"

# After the run, copy any txt files generated by LAMMPS back to the home space
if [ $(find $RUN_DIR_SCRATCH -name "*.txt" | wc -l) -gt 0 ]; then
    cp *.txt $RUN_DIR_HOME
fi

exit